Introduce ScopedConnectionHandle
KDAB/KDBindings pull request #31
Opened 2022-04-06 08:50 UTC by Waqar144

Currently we have to disconnect the slot ourselves when its not needed.
This is a bit error prone as we might forget to disconnect a slot in
some cases leading to use after frees and invalid reads.

This change proposes ScopedConnectionHandle which is a thin wrapper
over ConnectionHandle. It automatically disconnects on scope exit.

2022-04-08 14:50 UTC, LeonMatthesKDAB reviewed
Hi Waqar,

This is a great addition.
I'll add a few changes myself, then you can review my changes and merge:
1. Rename ScopedConnectionHandle -> ConnectionGuard - Inspired by ConnectionBlocker and std::lock_guard
2. Implement `ConnectionHandle* operator->()`
3. Remove the `void disconnect()`.

2022-04-08 14:56 UTC, Waqar144 commented
> Hi Waqar,
> 
> This is a great addition. I'll add a few changes myself, then you can review my changes and merge:
> 
> 1. Rename ScopedConnectionHandle -> ConnectionGuard - Inspired by ConnectionBlocker and std::lock_guard
> 2. Implement `ConnectionHandle* operator->()`
> 3. Remove the `void disconnect()`.

Sure, thanks.

2022-04-11 08:12 UTC, LeonMatthesKDAB commented
@Waqar144 I've implemented the changes, updated the docs a bit and added a few more tests.

Feel free to review.

2022-04-11 08:24 UTC, LeonMatthesKDAB requested changes
Another problem just came up, std::lock_guard is actually deprecated for scoped_lock in C++17.

Therefore it would be better to choose a name like ScopedConnection instead.
I'll do another rename... :roll_eyes:

2022-04-11 08:28 UTC, LeonMatthesKDAB approved these changes
Alright, finally good to go from my perspective now.

2022-04-11 10:01 UTC, Waqar144 commented
Looks good. 

Though I think the `handle()` function and its overload can probably be removed now as `operator->` is cleaner I think. But can be handled later I guess.

2022-04-11 10:02 UTC, merged